-- FIQT Reviews: docentes y asociaciones curso-docente de la malla cargada.
-- Fuente de carga inicial: capturas públicas proporcionadas por el usuario.
-- No incluye DNI, códigos internos, horarios, vacantes ni datos administrativos.

create unique index if not exists professors_full_name_unique
on public.professors(full_name);

with links(course_code, professor_name) as (
values
  ('BDI01', 'Morán Tello, Miguel'),
  ('BDI01', 'Tipacti Rodríguez, Paula'),
  ('BDI02', 'Morán Tello, Miguel'),
  ('BDI02', 'Tipacti Rodríguez, Paula'),
  ('BEF01', 'Mora Ramírez, Rafael'),
  ('BEG01', 'Castillo Prado, Jorge'),
  ('BEG01', 'Pinglo Ramírez, Miguel'),
  ('BFI01', 'Altuna Díaz, Isaac'),
  ('BFI01', 'Huamán Pérez, Fernando'),
  ('BFI01', 'Morales Chinchay, Julio'),
  ('BFI01', 'Mosquera Molina, Miguel'),
  ('BFI01', 'Paria Sena, Robert'),
  ('BFI02', 'Altuna Díaz, Isaac'),
  ('BFI02', 'Huamán Pérez, Fernando'),
  ('BFI02', 'Morales Chinchay, Julio'),
  ('BFI02', 'Paria Sena, Robert'),
  ('BFI02', 'Sánchez Dávalos, Juan'),
  ('BFI03', 'Altuna Díaz, Isaac'),
  ('BFI03', 'Carhuancho Lucen, Ciro'),
  ('BFI03', 'Huamán Pérez, Fernando'),
  ('BFI03', 'Paria Sena, Robert'),
  ('BFI04', 'Carhuancho Lucen, Ciro'),
  ('BFI04', 'Mosquera Molina, Miguel'),
  ('BIC01', 'Molina Tarazona, Lucy'),
  ('BIC01', 'Norabuena Meza, Edgar'),
  ('BMA01', 'Arredondo Ruiz, Manuel'),
  ('BMA01', 'Madueño Sulca, César'),
  ('BMA01', 'Palomino Vildoso, Rolando'),
  ('BMA01', 'Tineo Córdova, Freddy'),
  ('BMA02', 'Escalante Huamaní, Sonia'),
  ('BMA02', 'Flores Salinas, José'),
  ('BMA02', 'Palomino Vildoso, Rolando'),
  ('BMA02', 'Tineo Córdova, Freddy'),
  ('BMA03', 'Arredondo Ruiz, Manuel'),
  ('BMA03', 'Herbozo y Romero, César'),
  ('BMA03', 'Madueño Sulca, César'),
  ('BMA03', 'Palomino Vildoso, Rolando'),
  ('BMA03', 'Tineo Córdova, Freddy'),
  ('BMA03', 'Zamora Córdova, John'),
  ('BMA04', 'Escalante Huamaní, Sonia'),
  ('BMA04', 'Madueño Sulca, César'),
  ('BMA04', 'Tineo Córdova, Freddy'),
  ('BMA05', 'Flores Salinas, José'),
  ('BMA05', 'Herbozo y Romero, César'),
  ('BMA06', 'Flores Salinas, José'),
  ('BMA06', 'Herbozo y Romero, César'),
  ('BQU01', 'Benites Mitma, Willman Vicente'),
  ('BQU01', 'Breña Ore, Jorge Luis'),
  ('BQU01', 'Carbajal Gutiérrez, Félix'),
  ('BQU01', 'Cárdenas Vargas, Bertha'),
  ('BQU01', 'Castillo Gomero, Elifio Gustavo'),
  ('BQU01', 'Flores Ramos, Jaime'),
  ('BQU01', 'Garay Sifuentes, Juan'),
  ('BQU01', 'Nieto Juárez, Jéssica Ivana'),
  ('BQU02', 'Benites Mitma, Willman Vicente'),
  ('BQU02', 'Castillo Gomero, Elifio Gustavo'),
  ('BQU02', 'Flores Ramos, Jaime'),
  ('BQU02', 'Garayar Ávalos, Mario'),
  ('BRC01', 'Rivera Zamudio, July'),
  ('BRC01', 'Ruiz Gubiel, Víctor'),
  ('BRN01', 'Delgado Garro, Pamela'),
  ('BRN01', 'Ramos Balcázar, Yone'),
  ('EC618', 'Carabali Gutiérrez, Félix'),
  ('EC618', 'Vergara Pata, Eduardo'),
  ('EE103', 'Vega Zapata, Eduardo'),
  ('EP308', 'Castillo Prado, Jorge'),
  ('EP308', 'Pinglo Ramírez, Miguel'),
  ('EP818', 'Aguilar Loyaga, Santiago'),
  ('MA613', 'Ramos Balcázar, Yone'),
  ('MA613', 'Ríos Varillas, Cecilia'),
  ('MA713', 'Norabuena Meza, Edgar'),
  ('MA713', 'Sierra Flores, Luis'),
  ('MA713', 'Zamora Córdova, John'),
  ('PA113', 'Espinda Veliz, Jorge'),
  ('PA113', 'Franco Portilla, Luz'),
  ('PA136', 'Carreño León, Gustavo'),
  ('PA136', 'Espinda Veliz, Jorge'),
  ('PA136', 'Franco Portilla, Luz'),
  ('PA714', 'Franco Portilla, Luz'),
  ('PA714', 'Pérez Estrella, Mauro'),
  ('PA714', 'Zamora Córdova, John'),
  ('PI111', 'De la Cruz Azabache, Hilario Ricardo'),
  ('PI135', 'Álvarez Núñez, Emilia Antonia'),
  ('PI135', 'Apaza Huancapaza, Ubaldo'),
  ('PI135', 'Garayar Ávalos, Mario'),
  ('PI135', 'Turriate Manrique, Juan Ángel'),
  ('PI135', 'Vergara Sotomayor, Abel Fernando'),
  ('PI135', 'Vivas Cuellar, Magali Camilla'),
  ('PI136', 'Collado Domínguez, Elverson Alcides'),
  ('PI136', 'Marcelo Astocondor, Dionicio Adolfo'),
  ('PI136', 'Neira Montoya, Enrique Filiberto'),
  ('PI136', 'Vergara Sotomayor, Abel Fernando'),
  ('PI136', 'Villón Ulloa, Ángel Eduardo'),
  ('PI140', 'Reátegui Romero, Warren'),
  ('PI140', 'Zaldivar Álvarez, Walter Fernando'),
  ('PI142', 'Ortiz Guzmán, Rommel Hans'),
  ('PI142', 'Pilco Núñez, Alex Willy'),
  ('PI142', 'Vivas Cuellar, Magali Camilla'),
  ('PI143', 'Ramos Julián, Aldan'),
  ('PI143', 'Salinas García, Julia Victoria'),
  ('PI144', 'Montalvo Hurtado, Celso Pastor Alejandro'),
  ('PI144', 'Ortiz Guzmán, Rommel Hans'),
  ('PI146', 'Dextre Jara, Edwin Tellez'),
  ('PI146', 'Villón Ulloa, Ángel Eduardo'),
  ('PI216', 'Apaza Huancapaza, Ubaldo'),
  ('PI216', 'Gago Tolentino, Roger Enrique'),
  ('PI217', 'Apaza Huancapaza, Ubaldo'),
  ('PI217', 'Huayta Socantaype, Fredy Vicente'),
  ('PI225', 'Gago Tolentino, Roger Enrique'),
  ('PI225', 'Ortiz Guzmán, Rommel Hans'),
  ('PI225', 'Osorio Carrera, César Javier'),
  ('PI318', 'Castillo Gomero, Elifio Gustavo'),
  ('PI318', 'Reátegui Romero, Warren'),
  ('PI365', 'Chirre Flores, Jaqueline'),
  ('PI365', 'Zaldivar Álvarez, Walter Fernando'),
  ('PI415', 'Álvarez Núñez, Emilia Antonia'),
  ('PI415', 'Collado Domínguez, Elverson Alcides'),
  ('PI415', 'Vivas Cuellar, Magali Camilla'),
  ('PI426', 'Dextre Jara, Edwin Tellez'),
  ('PI426', 'Montalvo Hurtado, Celso Pastor Alejandro'),
  ('PI426', 'Wong Dávila, Jorge Luis'),
  ('PI510', 'Carbajal González, Arsedio Oswaldo'),
  ('PI510', 'Porras Sosa, Emilio'),
  ('PI514', 'Paucar Cuba, Karin María'),
  ('PI514', 'Vergara Sotomayor, Abel Fernando'),
  ('PI520', 'Collantes Díaz, Ingrid Elida'),
  ('PI520', 'Ramos Julián, Aldan'),
  ('PI521', 'Neira Montoya, Enrique Filiberto'),
  ('PI521', 'Wong Dávila, Jorge Luis'),
  ('PI524', 'Dávila Tapia, José Vicente'),
  ('PI524', 'Pilco Núñez, Alex Willy'),
  ('PI525', 'Delgado Acevedo, Aldo Max'),
  ('PI525', 'Huayta Socantaype, Fredy Vicente'),
  ('PI525', 'Salinas García, Julia Victoria'),
  ('PI525', 'Wong Dávila, Jorge Luis'),
  ('PI555', 'Canchucaja Cruz, Ramiro Félix'),
  ('PI555', 'Wong Dávila, Jorge Luis'),
  ('PI911', 'Dextre Jara, Edwin Tellez'),
  ('PI911', 'Marcelo Astocondor, Dionicio Adolfo'),
  ('QT714', 'Collado Domínguez, Elverson Alcides'),
  ('QT714', 'Marcelo Astocondor, Dionicio Adolfo'),
  ('QT714', 'Pilco Núñez, Alex Willy'),
  ('QT715', 'Delgado Acevedo, Aldo Max'),
  ('QT715', 'Hermoza Guerra, Emilia Gabriela'),
  ('QT715', 'Paján Lan, Harold Patrick'),
  ('QT715', 'Pérez Estrella, Mauro'),
  ('QU216', 'Benites Mitma, Willman Vicente'),
  ('QU216', 'Cárdenas Vargas, Bertha'),
  ('QU216', 'Castillo Gomero, Elifio Gustavo'),
  ('QU216', 'Jaramillo Saldaña, Fernando Amade'),
  ('QU216', 'Quiroz García, Juan Antonio'),
  ('QU328', 'Breña Ore, Jorge Luis'),
  ('QU328', 'Bullón Camarena, Olga Frida'),
  ('QU328', 'Collantes Díaz, Ingrid Elida'),
  ('QU328', 'Hermoza Guerra, Emilia Gabriela'),
  ('QU338', 'Breña Ore, Jorge Luis'),
  ('QU338', 'Bullón Camarena, Olga Frida'),
  ('QU338', 'Neira Montoya, Enrique Filiberto'),
  ('QU427', 'Álvarez Núñez, Emilia Antonia'),
  ('QU427', 'Cárdenas Mendoza, Teodardo Javier'),
  ('QU427', 'Jaramillo Saldaña, Fernando Amade'),
  ('QU427', 'Rojas Orosco, Janet'),
  ('QU428', 'Cárdenas Mendoza, Teodardo Javier'),
  ('QU428', 'Huayta Socantaype, Fredy Vicente'),
  ('QU428', 'Jaramillo Saldaña, Fernando Amade'),
  ('QU428', 'Rodríguez Carbajal, Genaro Arilando'),
  ('QU428', 'Rojas Orosco, Janet'),
  ('QU518', 'Cárdenas Vargas, Bertha'),
  ('QU518', 'Garayar Ávalos, Mario'),
  ('QU518', 'Quiroz García, Juan Antonio'),
  ('QU518', 'Rodríguez Carbajal, Genaro Arilando'),
  ('QU518', 'Tuesta Chávez, Tarsila')
)
insert into public.professors(full_name, source_name, is_active)
select distinct professor_name, 'DIRCE UNI', true
from links
on conflict (full_name) do update set
  source_name = excluded.source_name,
  is_active = true;

with links(course_code, professor_name) as (
values
  ('BDI01', 'Morán Tello, Miguel'),
  ('BDI01', 'Tipacti Rodríguez, Paula'),
  ('BDI02', 'Morán Tello, Miguel'),
  ('BDI02', 'Tipacti Rodríguez, Paula'),
  ('BEF01', 'Mora Ramírez, Rafael'),
  ('BEG01', 'Castillo Prado, Jorge'),
  ('BEG01', 'Pinglo Ramírez, Miguel'),
  ('BFI01', 'Altuna Díaz, Isaac'),
  ('BFI01', 'Huamán Pérez, Fernando'),
  ('BFI01', 'Morales Chinchay, Julio'),
  ('BFI01', 'Mosquera Molina, Miguel'),
  ('BFI01', 'Paria Sena, Robert'),
  ('BFI02', 'Altuna Díaz, Isaac'),
  ('BFI02', 'Huamán Pérez, Fernando'),
  ('BFI02', 'Morales Chinchay, Julio'),
  ('BFI02', 'Paria Sena, Robert'),
  ('BFI02', 'Sánchez Dávalos, Juan'),
  ('BFI03', 'Altuna Díaz, Isaac'),
  ('BFI03', 'Carhuancho Lucen, Ciro'),
  ('BFI03', 'Huamán Pérez, Fernando'),
  ('BFI03', 'Paria Sena, Robert'),
  ('BFI04', 'Carhuancho Lucen, Ciro'),
  ('BFI04', 'Mosquera Molina, Miguel'),
  ('BIC01', 'Molina Tarazona, Lucy'),
  ('BIC01', 'Norabuena Meza, Edgar'),
  ('BMA01', 'Arredondo Ruiz, Manuel'),
  ('BMA01', 'Madueño Sulca, César'),
  ('BMA01', 'Palomino Vildoso, Rolando'),
  ('BMA01', 'Tineo Córdova, Freddy'),
  ('BMA02', 'Escalante Huamaní, Sonia'),
  ('BMA02', 'Flores Salinas, José'),
  ('BMA02', 'Palomino Vildoso, Rolando'),
  ('BMA02', 'Tineo Córdova, Freddy'),
  ('BMA03', 'Arredondo Ruiz, Manuel'),
  ('BMA03', 'Herbozo y Romero, César'),
  ('BMA03', 'Madueño Sulca, César'),
  ('BMA03', 'Palomino Vildoso, Rolando'),
  ('BMA03', 'Tineo Córdova, Freddy'),
  ('BMA03', 'Zamora Córdova, John'),
  ('BMA04', 'Escalante Huamaní, Sonia'),
  ('BMA04', 'Madueño Sulca, César'),
  ('BMA04', 'Tineo Córdova, Freddy'),
  ('BMA05', 'Flores Salinas, José'),
  ('BMA05', 'Herbozo y Romero, César'),
  ('BMA06', 'Flores Salinas, José'),
  ('BMA06', 'Herbozo y Romero, César'),
  ('BQU01', 'Benites Mitma, Willman Vicente'),
  ('BQU01', 'Breña Ore, Jorge Luis'),
  ('BQU01', 'Carbajal Gutiérrez, Félix'),
  ('BQU01', 'Cárdenas Vargas, Bertha'),
  ('BQU01', 'Castillo Gomero, Elifio Gustavo'),
  ('BQU01', 'Flores Ramos, Jaime'),
  ('BQU01', 'Garay Sifuentes, Juan'),
  ('BQU01', 'Nieto Juárez, Jéssica Ivana'),
  ('BQU02', 'Benites Mitma, Willman Vicente'),
  ('BQU02', 'Castillo Gomero, Elifio Gustavo'),
  ('BQU02', 'Flores Ramos, Jaime'),
  ('BQU02', 'Garayar Ávalos, Mario'),
  ('BRC01', 'Rivera Zamudio, July'),
  ('BRC01', 'Ruiz Gubiel, Víctor'),
  ('BRN01', 'Delgado Garro, Pamela'),
  ('BRN01', 'Ramos Balcázar, Yone'),
  ('EC618', 'Carabali Gutiérrez, Félix'),
  ('EC618', 'Vergara Pata, Eduardo'),
  ('EE103', 'Vega Zapata, Eduardo'),
  ('EP308', 'Castillo Prado, Jorge'),
  ('EP308', 'Pinglo Ramírez, Miguel'),
  ('EP818', 'Aguilar Loyaga, Santiago'),
  ('MA613', 'Ramos Balcázar, Yone'),
  ('MA613', 'Ríos Varillas, Cecilia'),
  ('MA713', 'Norabuena Meza, Edgar'),
  ('MA713', 'Sierra Flores, Luis'),
  ('MA713', 'Zamora Córdova, John'),
  ('PA113', 'Espinda Veliz, Jorge'),
  ('PA113', 'Franco Portilla, Luz'),
  ('PA136', 'Carreño León, Gustavo'),
  ('PA136', 'Espinda Veliz, Jorge'),
  ('PA136', 'Franco Portilla, Luz'),
  ('PA714', 'Franco Portilla, Luz'),
  ('PA714', 'Pérez Estrella, Mauro'),
  ('PA714', 'Zamora Córdova, John'),
  ('PI111', 'De la Cruz Azabache, Hilario Ricardo'),
  ('PI135', 'Álvarez Núñez, Emilia Antonia'),
  ('PI135', 'Apaza Huancapaza, Ubaldo'),
  ('PI135', 'Garayar Ávalos, Mario'),
  ('PI135', 'Turriate Manrique, Juan Ángel'),
  ('PI135', 'Vergara Sotomayor, Abel Fernando'),
  ('PI135', 'Vivas Cuellar, Magali Camilla'),
  ('PI136', 'Collado Domínguez, Elverson Alcides'),
  ('PI136', 'Marcelo Astocondor, Dionicio Adolfo'),
  ('PI136', 'Neira Montoya, Enrique Filiberto'),
  ('PI136', 'Vergara Sotomayor, Abel Fernando'),
  ('PI136', 'Villón Ulloa, Ángel Eduardo'),
  ('PI140', 'Reátegui Romero, Warren'),
  ('PI140', 'Zaldivar Álvarez, Walter Fernando'),
  ('PI142', 'Ortiz Guzmán, Rommel Hans'),
  ('PI142', 'Pilco Núñez, Alex Willy'),
  ('PI142', 'Vivas Cuellar, Magali Camilla'),
  ('PI143', 'Ramos Julián, Aldan'),
  ('PI143', 'Salinas García, Julia Victoria'),
  ('PI144', 'Montalvo Hurtado, Celso Pastor Alejandro'),
  ('PI144', 'Ortiz Guzmán, Rommel Hans'),
  ('PI146', 'Dextre Jara, Edwin Tellez'),
  ('PI146', 'Villón Ulloa, Ángel Eduardo'),
  ('PI216', 'Apaza Huancapaza, Ubaldo'),
  ('PI216', 'Gago Tolentino, Roger Enrique'),
  ('PI217', 'Apaza Huancapaza, Ubaldo'),
  ('PI217', 'Huayta Socantaype, Fredy Vicente'),
  ('PI225', 'Gago Tolentino, Roger Enrique'),
  ('PI225', 'Ortiz Guzmán, Rommel Hans'),
  ('PI225', 'Osorio Carrera, César Javier'),
  ('PI318', 'Castillo Gomero, Elifio Gustavo'),
  ('PI318', 'Reátegui Romero, Warren'),
  ('PI365', 'Chirre Flores, Jaqueline'),
  ('PI365', 'Zaldivar Álvarez, Walter Fernando'),
  ('PI415', 'Álvarez Núñez, Emilia Antonia'),
  ('PI415', 'Collado Domínguez, Elverson Alcides'),
  ('PI415', 'Vivas Cuellar, Magali Camilla'),
  ('PI426', 'Dextre Jara, Edwin Tellez'),
  ('PI426', 'Montalvo Hurtado, Celso Pastor Alejandro'),
  ('PI426', 'Wong Dávila, Jorge Luis'),
  ('PI510', 'Carbajal González, Arsedio Oswaldo'),
  ('PI510', 'Porras Sosa, Emilio'),
  ('PI514', 'Paucar Cuba, Karin María'),
  ('PI514', 'Vergara Sotomayor, Abel Fernando'),
  ('PI520', 'Collantes Díaz, Ingrid Elida'),
  ('PI520', 'Ramos Julián, Aldan'),
  ('PI521', 'Neira Montoya, Enrique Filiberto'),
  ('PI521', 'Wong Dávila, Jorge Luis'),
  ('PI524', 'Dávila Tapia, José Vicente'),
  ('PI524', 'Pilco Núñez, Alex Willy'),
  ('PI525', 'Delgado Acevedo, Aldo Max'),
  ('PI525', 'Huayta Socantaype, Fredy Vicente'),
  ('PI525', 'Salinas García, Julia Victoria'),
  ('PI525', 'Wong Dávila, Jorge Luis'),
  ('PI555', 'Canchucaja Cruz, Ramiro Félix'),
  ('PI555', 'Wong Dávila, Jorge Luis'),
  ('PI911', 'Dextre Jara, Edwin Tellez'),
  ('PI911', 'Marcelo Astocondor, Dionicio Adolfo'),
  ('QT714', 'Collado Domínguez, Elverson Alcides'),
  ('QT714', 'Marcelo Astocondor, Dionicio Adolfo'),
  ('QT714', 'Pilco Núñez, Alex Willy'),
  ('QT715', 'Delgado Acevedo, Aldo Max'),
  ('QT715', 'Hermoza Guerra, Emilia Gabriela'),
  ('QT715', 'Paján Lan, Harold Patrick'),
  ('QT715', 'Pérez Estrella, Mauro'),
  ('QU216', 'Benites Mitma, Willman Vicente'),
  ('QU216', 'Cárdenas Vargas, Bertha'),
  ('QU216', 'Castillo Gomero, Elifio Gustavo'),
  ('QU216', 'Jaramillo Saldaña, Fernando Amade'),
  ('QU216', 'Quiroz García, Juan Antonio'),
  ('QU328', 'Breña Ore, Jorge Luis'),
  ('QU328', 'Bullón Camarena, Olga Frida'),
  ('QU328', 'Collantes Díaz, Ingrid Elida'),
  ('QU328', 'Hermoza Guerra, Emilia Gabriela'),
  ('QU338', 'Breña Ore, Jorge Luis'),
  ('QU338', 'Bullón Camarena, Olga Frida'),
  ('QU338', 'Neira Montoya, Enrique Filiberto'),
  ('QU427', 'Álvarez Núñez, Emilia Antonia'),
  ('QU427', 'Cárdenas Mendoza, Teodardo Javier'),
  ('QU427', 'Jaramillo Saldaña, Fernando Amade'),
  ('QU427', 'Rojas Orosco, Janet'),
  ('QU428', 'Cárdenas Mendoza, Teodardo Javier'),
  ('QU428', 'Huayta Socantaype, Fredy Vicente'),
  ('QU428', 'Jaramillo Saldaña, Fernando Amade'),
  ('QU428', 'Rodríguez Carbajal, Genaro Arilando'),
  ('QU428', 'Rojas Orosco, Janet'),
  ('QU518', 'Cárdenas Vargas, Bertha'),
  ('QU518', 'Garayar Ávalos, Mario'),
  ('QU518', 'Quiroz García, Juan Antonio'),
  ('QU518', 'Rodríguez Carbajal, Genaro Arilando'),
  ('QU518', 'Tuesta Chávez, Tarsila')
)
insert into public.course_professors(course_id, professor_id)
select c.id, p.id
from links l
join public.courses c on c.code = l.course_code
join public.professors p on p.full_name = l.professor_name
where not exists (
  select 1
  from public.course_professors cp
  where cp.course_id = c.id
    and cp.professor_id = p.id
);

select
  c.code,
  c.name as curso,
  count(cp.professor_id) as profesores_asociados
from public.courses c
left join public.course_professors cp on cp.course_id = c.id
where c.code in (select distinct course_code from (values
  ('BDI01', 'Morán Tello, Miguel'),
  ('BDI01', 'Tipacti Rodríguez, Paula'),
  ('BDI02', 'Morán Tello, Miguel'),
  ('BDI02', 'Tipacti Rodríguez, Paula'),
  ('BEF01', 'Mora Ramírez, Rafael'),
  ('BEG01', 'Castillo Prado, Jorge'),
  ('BEG01', 'Pinglo Ramírez, Miguel'),
  ('BFI01', 'Altuna Díaz, Isaac'),
  ('BFI01', 'Huamán Pérez, Fernando'),
  ('BFI01', 'Morales Chinchay, Julio'),
  ('BFI01', 'Mosquera Molina, Miguel'),
  ('BFI01', 'Paria Sena, Robert'),
  ('BFI02', 'Altuna Díaz, Isaac'),
  ('BFI02', 'Huamán Pérez, Fernando'),
  ('BFI02', 'Morales Chinchay, Julio'),
  ('BFI02', 'Paria Sena, Robert'),
  ('BFI02', 'Sánchez Dávalos, Juan'),
  ('BFI03', 'Altuna Díaz, Isaac'),
  ('BFI03', 'Carhuancho Lucen, Ciro'),
  ('BFI03', 'Huamán Pérez, Fernando'),
  ('BFI03', 'Paria Sena, Robert'),
  ('BFI04', 'Carhuancho Lucen, Ciro'),
  ('BFI04', 'Mosquera Molina, Miguel'),
  ('BIC01', 'Molina Tarazona, Lucy'),
  ('BIC01', 'Norabuena Meza, Edgar'),
  ('BMA01', 'Arredondo Ruiz, Manuel'),
  ('BMA01', 'Madueño Sulca, César'),
  ('BMA01', 'Palomino Vildoso, Rolando'),
  ('BMA01', 'Tineo Córdova, Freddy'),
  ('BMA02', 'Escalante Huamaní, Sonia'),
  ('BMA02', 'Flores Salinas, José'),
  ('BMA02', 'Palomino Vildoso, Rolando'),
  ('BMA02', 'Tineo Córdova, Freddy'),
  ('BMA03', 'Arredondo Ruiz, Manuel'),
  ('BMA03', 'Herbozo y Romero, César'),
  ('BMA03', 'Madueño Sulca, César'),
  ('BMA03', 'Palomino Vildoso, Rolando'),
  ('BMA03', 'Tineo Córdova, Freddy'),
  ('BMA03', 'Zamora Córdova, John'),
  ('BMA04', 'Escalante Huamaní, Sonia'),
  ('BMA04', 'Madueño Sulca, César'),
  ('BMA04', 'Tineo Córdova, Freddy'),
  ('BMA05', 'Flores Salinas, José'),
  ('BMA05', 'Herbozo y Romero, César'),
  ('BMA06', 'Flores Salinas, José'),
  ('BMA06', 'Herbozo y Romero, César'),
  ('BQU01', 'Benites Mitma, Willman Vicente'),
  ('BQU01', 'Breña Ore, Jorge Luis'),
  ('BQU01', 'Carbajal Gutiérrez, Félix'),
  ('BQU01', 'Cárdenas Vargas, Bertha'),
  ('BQU01', 'Castillo Gomero, Elifio Gustavo'),
  ('BQU01', 'Flores Ramos, Jaime'),
  ('BQU01', 'Garay Sifuentes, Juan'),
  ('BQU01', 'Nieto Juárez, Jéssica Ivana'),
  ('BQU02', 'Benites Mitma, Willman Vicente'),
  ('BQU02', 'Castillo Gomero, Elifio Gustavo'),
  ('BQU02', 'Flores Ramos, Jaime'),
  ('BQU02', 'Garayar Ávalos, Mario'),
  ('BRC01', 'Rivera Zamudio, July'),
  ('BRC01', 'Ruiz Gubiel, Víctor'),
  ('BRN01', 'Delgado Garro, Pamela'),
  ('BRN01', 'Ramos Balcázar, Yone'),
  ('EC618', 'Carabali Gutiérrez, Félix'),
  ('EC618', 'Vergara Pata, Eduardo'),
  ('EE103', 'Vega Zapata, Eduardo'),
  ('EP308', 'Castillo Prado, Jorge'),
  ('EP308', 'Pinglo Ramírez, Miguel'),
  ('EP818', 'Aguilar Loyaga, Santiago'),
  ('MA613', 'Ramos Balcázar, Yone'),
  ('MA613', 'Ríos Varillas, Cecilia'),
  ('MA713', 'Norabuena Meza, Edgar'),
  ('MA713', 'Sierra Flores, Luis'),
  ('MA713', 'Zamora Córdova, John'),
  ('PA113', 'Espinda Veliz, Jorge'),
  ('PA113', 'Franco Portilla, Luz'),
  ('PA136', 'Carreño León, Gustavo'),
  ('PA136', 'Espinda Veliz, Jorge'),
  ('PA136', 'Franco Portilla, Luz'),
  ('PA714', 'Franco Portilla, Luz'),
  ('PA714', 'Pérez Estrella, Mauro'),
  ('PA714', 'Zamora Córdova, John'),
  ('PI111', 'De la Cruz Azabache, Hilario Ricardo'),
  ('PI135', 'Álvarez Núñez, Emilia Antonia'),
  ('PI135', 'Apaza Huancapaza, Ubaldo'),
  ('PI135', 'Garayar Ávalos, Mario'),
  ('PI135', 'Turriate Manrique, Juan Ángel'),
  ('PI135', 'Vergara Sotomayor, Abel Fernando'),
  ('PI135', 'Vivas Cuellar, Magali Camilla'),
  ('PI136', 'Collado Domínguez, Elverson Alcides'),
  ('PI136', 'Marcelo Astocondor, Dionicio Adolfo'),
  ('PI136', 'Neira Montoya, Enrique Filiberto'),
  ('PI136', 'Vergara Sotomayor, Abel Fernando'),
  ('PI136', 'Villón Ulloa, Ángel Eduardo'),
  ('PI140', 'Reátegui Romero, Warren'),
  ('PI140', 'Zaldivar Álvarez, Walter Fernando'),
  ('PI142', 'Ortiz Guzmán, Rommel Hans'),
  ('PI142', 'Pilco Núñez, Alex Willy'),
  ('PI142', 'Vivas Cuellar, Magali Camilla'),
  ('PI143', 'Ramos Julián, Aldan'),
  ('PI143', 'Salinas García, Julia Victoria'),
  ('PI144', 'Montalvo Hurtado, Celso Pastor Alejandro'),
  ('PI144', 'Ortiz Guzmán, Rommel Hans'),
  ('PI146', 'Dextre Jara, Edwin Tellez'),
  ('PI146', 'Villón Ulloa, Ángel Eduardo'),
  ('PI216', 'Apaza Huancapaza, Ubaldo'),
  ('PI216', 'Gago Tolentino, Roger Enrique'),
  ('PI217', 'Apaza Huancapaza, Ubaldo'),
  ('PI217', 'Huayta Socantaype, Fredy Vicente'),
  ('PI225', 'Gago Tolentino, Roger Enrique'),
  ('PI225', 'Ortiz Guzmán, Rommel Hans'),
  ('PI225', 'Osorio Carrera, César Javier'),
  ('PI318', 'Castillo Gomero, Elifio Gustavo'),
  ('PI318', 'Reátegui Romero, Warren'),
  ('PI365', 'Chirre Flores, Jaqueline'),
  ('PI365', 'Zaldivar Álvarez, Walter Fernando'),
  ('PI415', 'Álvarez Núñez, Emilia Antonia'),
  ('PI415', 'Collado Domínguez, Elverson Alcides'),
  ('PI415', 'Vivas Cuellar, Magali Camilla'),
  ('PI426', 'Dextre Jara, Edwin Tellez'),
  ('PI426', 'Montalvo Hurtado, Celso Pastor Alejandro'),
  ('PI426', 'Wong Dávila, Jorge Luis'),
  ('PI510', 'Carbajal González, Arsedio Oswaldo'),
  ('PI510', 'Porras Sosa, Emilio'),
  ('PI514', 'Paucar Cuba, Karin María'),
  ('PI514', 'Vergara Sotomayor, Abel Fernando'),
  ('PI520', 'Collantes Díaz, Ingrid Elida'),
  ('PI520', 'Ramos Julián, Aldan'),
  ('PI521', 'Neira Montoya, Enrique Filiberto'),
  ('PI521', 'Wong Dávila, Jorge Luis'),
  ('PI524', 'Dávila Tapia, José Vicente'),
  ('PI524', 'Pilco Núñez, Alex Willy'),
  ('PI525', 'Delgado Acevedo, Aldo Max'),
  ('PI525', 'Huayta Socantaype, Fredy Vicente'),
  ('PI525', 'Salinas García, Julia Victoria'),
  ('PI525', 'Wong Dávila, Jorge Luis'),
  ('PI555', 'Canchucaja Cruz, Ramiro Félix'),
  ('PI555', 'Wong Dávila, Jorge Luis'),
  ('PI911', 'Dextre Jara, Edwin Tellez'),
  ('PI911', 'Marcelo Astocondor, Dionicio Adolfo'),
  ('QT714', 'Collado Domínguez, Elverson Alcides'),
  ('QT714', 'Marcelo Astocondor, Dionicio Adolfo'),
  ('QT714', 'Pilco Núñez, Alex Willy'),
  ('QT715', 'Delgado Acevedo, Aldo Max'),
  ('QT715', 'Hermoza Guerra, Emilia Gabriela'),
  ('QT715', 'Paján Lan, Harold Patrick'),
  ('QT715', 'Pérez Estrella, Mauro'),
  ('QU216', 'Benites Mitma, Willman Vicente'),
  ('QU216', 'Cárdenas Vargas, Bertha'),
  ('QU216', 'Castillo Gomero, Elifio Gustavo'),
  ('QU216', 'Jaramillo Saldaña, Fernando Amade'),
  ('QU216', 'Quiroz García, Juan Antonio'),
  ('QU328', 'Breña Ore, Jorge Luis'),
  ('QU328', 'Bullón Camarena, Olga Frida'),
  ('QU328', 'Collantes Díaz, Ingrid Elida'),
  ('QU328', 'Hermoza Guerra, Emilia Gabriela'),
  ('QU338', 'Breña Ore, Jorge Luis'),
  ('QU338', 'Bullón Camarena, Olga Frida'),
  ('QU338', 'Neira Montoya, Enrique Filiberto'),
  ('QU427', 'Álvarez Núñez, Emilia Antonia'),
  ('QU427', 'Cárdenas Mendoza, Teodardo Javier'),
  ('QU427', 'Jaramillo Saldaña, Fernando Amade'),
  ('QU427', 'Rojas Orosco, Janet'),
  ('QU428', 'Cárdenas Mendoza, Teodardo Javier'),
  ('QU428', 'Huayta Socantaype, Fredy Vicente'),
  ('QU428', 'Jaramillo Saldaña, Fernando Amade'),
  ('QU428', 'Rodríguez Carbajal, Genaro Arilando'),
  ('QU428', 'Rojas Orosco, Janet'),
  ('QU518', 'Cárdenas Vargas, Bertha'),
  ('QU518', 'Garayar Ávalos, Mario'),
  ('QU518', 'Quiroz García, Juan Antonio'),
  ('QU518', 'Rodríguez Carbajal, Genaro Arilando'),
  ('QU518', 'Tuesta Chávez, Tarsila')
) as links(course_code, professor_name))
group by c.code, c.name
order by c.code;
