import { createClient } from '@/lib/supabase/server';
import type { Course, Cycle, Professor, Review } from '@/lib/types';
import { demoCourseProfessors, demoCourses, demoCycles, demoProfessors, isSupabaseConfigured } from '@/lib/demo';

export async function getCycles(): Promise<Cycle[]> { if (!isSupabaseConfigured) return demoCycles; const db = await createClient(); const { data } = await db.from('cycles').select('*').order('number'); return (data as Cycle[]) ?? []; }
export async function getCourses(cycleId: string): Promise<Course[]> { if (!isSupabaseConfigured) return demoCourses.filter(c => String(c.cycle_id) === cycleId); const db = await createClient(); const { data } = await db.from('courses').select('*').eq('cycle_id', cycleId).order('name'); return (data as Course[]) ?? []; }
export async function getCourse(id: string): Promise<Course | null> { if (!isSupabaseConfigured) return demoCourses.find(c => c.id === id) ?? null; const db = await createClient(); const { data } = await db.from('courses').select('*').eq('id', id).single(); return data as Course | null; }
export async function getCourseProfessors(courseId: string): Promise<Professor[]> { if (!isSupabaseConfigured) { const professorIds = new Set(demoCourseProfessors.filter(link => link.course_id === courseId).map(link => link.professor_id)); return demoProfessors.filter(p => professorIds.has(p.id)); } const db = await createClient(); const { data } = await db.from('course_professors').select('professors(*)').eq('course_id', courseId); return (data ?? []).flatMap((x: { professors: Professor | Professor[] | null }) => !x.professors ? [] : Array.isArray(x.professors) ? x.professors : [x.professors]); }
export async function getProfessor(id: string): Promise<Professor | null> { if (!isSupabaseConfigured) return demoProfessors.find(p => p.id === id) ?? null; const db = await createClient(); const { data } = await db.from('professors').select('*').eq('id', id).single(); return data as Professor | null; }
export async function getProfessorReviews(id: string): Promise<Review[]> { if (!isSupabaseConfigured) return []; const db = await createClient(); const { data } = await db.from('reviews').select('id,clarity_rating,difficulty_rating,fairness_rating,treatment_rating,workload_rating,recommendation,selected_tags,comment,created_at').eq('professor_id', id).eq('status', 'approved').order('created_at', { ascending: false }); return (data as Review[]) ?? []; }
