export type CourseProfessorEntry = {
  courseCode: string;
  professors: string[];
};

export const courseProfessorCatalog: CourseProfessorEntry[] = [
  { courseCode: 'BDI01', professors: ['Morán Tello, Miguel', 'Tipacti Rodríguez, Paula'] },
  { courseCode: 'BDI02', professors: ['Morán Tello, Miguel', 'Tipacti Rodríguez, Paula'] },
  { courseCode: 'BEF01', professors: ['Mora Ramírez, Rafael'] },
  { courseCode: 'BEG01', professors: ['Castillo Prado, Jorge', 'Pinglo Ramírez, Miguel'] },
  { courseCode: 'BFI01', professors: ['Altuna Díaz, Isaac', 'Huamán Pérez, Fernando', 'Morales Chinchay, Julio', 'Mosquera Molina, Miguel', 'Paria Sena, Robert'] },
  { courseCode: 'BFI02', professors: ['Altuna Díaz, Isaac', 'Huamán Pérez, Fernando', 'Morales Chinchay, Julio', 'Paria Sena, Robert', 'Sánchez Dávalos, Juan'] },
  { courseCode: 'BFI03', professors: ['Altuna Díaz, Isaac', 'Carhuancho Lucen, Ciro', 'Huamán Pérez, Fernando', 'Paria Sena, Robert'] },
  { courseCode: 'BFI04', professors: ['Carhuancho Lucen, Ciro', 'Mosquera Molina, Miguel'] },
  { courseCode: 'BIC01', professors: ['Molina Tarazona, Lucy', 'Norabuena Meza, Edgar'] },
  { courseCode: 'BMA01', professors: ['Arredondo Ruiz, Manuel', 'Madueño Sulca, César', 'Palomino Vildoso, Rolando', 'Tineo Córdova, Freddy'] },
  { courseCode: 'BMA02', professors: ['Escalante Huamaní, Sonia', 'Flores Salinas, José', 'Palomino Vildoso, Rolando', 'Tineo Córdova, Freddy'] },
  { courseCode: 'BMA03', professors: ['Arredondo Ruiz, Manuel', 'Herbozo y Romero, César', 'Madueño Sulca, César', 'Palomino Vildoso, Rolando', 'Tineo Córdova, Freddy', 'Zamora Córdova, John'] },
  { courseCode: 'BMA04', professors: ['Escalante Huamaní, Sonia', 'Madueño Sulca, César', 'Tineo Córdova, Freddy'] },
  { courseCode: 'BMA05', professors: ['Flores Salinas, José', 'Herbozo y Romero, César'] },
  { courseCode: 'BMA06', professors: ['Flores Salinas, José', 'Herbozo y Romero, César'] },
  { courseCode: 'BQU01', professors: ['Benites Mitma, Willman Vicente', 'Breña Ore, Jorge Luis', 'Carbajal Gutiérrez, Félix', 'Cárdenas Vargas, Bertha', 'Castillo Gomero, Elifio Gustavo', 'Flores Ramos, Jaime', 'Garay Sifuentes, Juan', 'Nieto Juárez, Jéssica Ivana'] },
  { courseCode: 'BQU02', professors: ['Benites Mitma, Willman Vicente', 'Castillo Gomero, Elifio Gustavo', 'Flores Ramos, Jaime', 'Garayar Ávalos, Mario'] },
  { courseCode: 'BRC01', professors: ['Rivera Zamudio, July', 'Ruiz Gubiel, Víctor'] },
  { courseCode: 'BRN01', professors: ['Delgado Garro, Pamela', 'Ramos Balcázar, Yone'] },
  { courseCode: 'EC618', professors: ['Carabali Gutiérrez, Félix', 'Vergara Pata, Eduardo'] },
  { courseCode: 'EE103', professors: ['Vega Zapata, Eduardo'] },
  { courseCode: 'EP308', professors: ['Castillo Prado, Jorge', 'Pinglo Ramírez, Miguel'] },
  { courseCode: 'EP818', professors: ['Aguilar Loyaga, Santiago'] },
  { courseCode: 'MA613', professors: ['Ramos Balcázar, Yone', 'Ríos Varillas, Cecilia'] },
  { courseCode: 'MA713', professors: ['Norabuena Meza, Edgar', 'Sierra Flores, Luis', 'Zamora Córdova, John'] },
  { courseCode: 'PA113', professors: ['Espinda Veliz, Jorge', 'Franco Portilla, Luz'] },
  { courseCode: 'PA136', professors: ['Carreño León, Gustavo', 'Espinda Veliz, Jorge', 'Franco Portilla, Luz'] },
  { courseCode: 'PA714', professors: ['Franco Portilla, Luz', 'Pérez Estrella, Mauro', 'Zamora Córdova, John'] },
  { courseCode: 'PI111', professors: ['De la Cruz Azabache, Hilario Ricardo'] },
  { courseCode: 'PI135', professors: ['Álvarez Núñez, Emilia Antonia', 'Apaza Huancapaza, Ubaldo', 'Garayar Ávalos, Mario', 'Turriate Manrique, Juan Ángel', 'Vergara Sotomayor, Abel Fernando', 'Vivas Cuellar, Magali Camilla'] },
  { courseCode: 'PI136', professors: ['Collado Domínguez, Elverson Alcides', 'Marcelo Astocondor, Dionicio Adolfo', 'Neira Montoya, Enrique Filiberto', 'Vergara Sotomayor, Abel Fernando', 'Villón Ulloa, Ángel Eduardo'] },
  { courseCode: 'PI140', professors: ['Reátegui Romero, Warren', 'Zaldivar Álvarez, Walter Fernando'] },
  { courseCode: 'PI142', professors: ['Ortiz Guzmán, Rommel Hans', 'Pilco Núñez, Alex Willy', 'Vivas Cuellar, Magali Camilla'] },
  { courseCode: 'PI143', professors: ['Ramos Julián, Aldan', 'Salinas García, Julia Victoria'] },
  { courseCode: 'PI144', professors: ['Montalvo Hurtado, Celso Pastor Alejandro', 'Ortiz Guzmán, Rommel Hans'] },
  { courseCode: 'PI146', professors: ['Dextre Jara, Edwin Tellez', 'Villón Ulloa, Ángel Eduardo'] },
  { courseCode: 'PI216', professors: ['Apaza Huancapaza, Ubaldo', 'Gago Tolentino, Roger Enrique'] },
  { courseCode: 'PI217', professors: ['Apaza Huancapaza, Ubaldo', 'Huayta Socantaype, Fredy Vicente'] },
  { courseCode: 'PI225', professors: ['Gago Tolentino, Roger Enrique', 'Ortiz Guzmán, Rommel Hans', 'Osorio Carrera, César Javier'] },
  { courseCode: 'PI318', professors: ['Castillo Gomero, Elifio Gustavo', 'Reátegui Romero, Warren'] },
  { courseCode: 'PI365', professors: ['Chirre Flores, Jaqueline', 'Zaldivar Álvarez, Walter Fernando'] },
  { courseCode: 'PI415', professors: ['Álvarez Núñez, Emilia Antonia', 'Collado Domínguez, Elverson Alcides', 'Vivas Cuellar, Magali Camilla'] },
  { courseCode: 'PI426', professors: ['Dextre Jara, Edwin Tellez', 'Montalvo Hurtado, Celso Pastor Alejandro', 'Wong Dávila, Jorge Luis'] },
  { courseCode: 'PI510', professors: ['Carbajal González, Arsedio Oswaldo', 'Porras Sosa, Emilio'] },
  { courseCode: 'PI514', professors: ['Paucar Cuba, Karin María', 'Vergara Sotomayor, Abel Fernando'] },
  { courseCode: 'PI520', professors: ['Collantes Díaz, Ingrid Elida', 'Ramos Julián, Aldan'] },
  { courseCode: 'PI521', professors: ['Neira Montoya, Enrique Filiberto', 'Wong Dávila, Jorge Luis'] },
  { courseCode: 'PI524', professors: ['Dávila Tapia, José Vicente', 'Pilco Núñez, Alex Willy'] },
  { courseCode: 'PI525', professors: ['Delgado Acevedo, Aldo Max', 'Huayta Socantaype, Fredy Vicente', 'Salinas García, Julia Victoria', 'Wong Dávila, Jorge Luis'] },
  { courseCode: 'PI555', professors: ['Canchucaja Cruz, Ramiro Félix', 'Wong Dávila, Jorge Luis'] },
  { courseCode: 'PI911', professors: ['Dextre Jara, Edwin Tellez', 'Marcelo Astocondor, Dionicio Adolfo'] },
  { courseCode: 'QT714', professors: ['Collado Domínguez, Elverson Alcides', 'Marcelo Astocondor, Dionicio Adolfo', 'Pilco Núñez, Alex Willy'] },
  { courseCode: 'QT715', professors: ['Delgado Acevedo, Aldo Max', 'Hermoza Guerra, Emilia Gabriela', 'Paján Lan, Harold Patrick', 'Pérez Estrella, Mauro'] },
  { courseCode: 'QU216', professors: ['Benites Mitma, Willman Vicente', 'Cárdenas Vargas, Bertha', 'Castillo Gomero, Elifio Gustavo', 'Jaramillo Saldaña, Fernando Amade', 'Quiroz García, Juan Antonio'] },
  { courseCode: 'QU328', professors: ['Breña Ore, Jorge Luis', 'Bullón Camarena, Olga Frida', 'Collantes Díaz, Ingrid Elida', 'Hermoza Guerra, Emilia Gabriela'] },
  { courseCode: 'QU338', professors: ['Breña Ore, Jorge Luis', 'Bullón Camarena, Olga Frida', 'Neira Montoya, Enrique Filiberto'] },
  { courseCode: 'QU427', professors: ['Álvarez Núñez, Emilia Antonia', 'Cárdenas Mendoza, Teodardo Javier', 'Jaramillo Saldaña, Fernando Amade', 'Rojas Orosco, Janet'] },
  { courseCode: 'QU428', professors: ['Cárdenas Mendoza, Teodardo Javier', 'Huayta Socantaype, Fredy Vicente', 'Jaramillo Saldaña, Fernando Amade', 'Rodríguez Carbajal, Genaro Arilando', 'Rojas Orosco, Janet'] },
  { courseCode: 'QU518', professors: ['Cárdenas Vargas, Bertha', 'Garayar Ávalos, Mario', 'Quiroz García, Juan Antonio', 'Rodríguez Carbajal, Genaro Arilando', 'Tuesta Chávez, Tarsila'] }
];

export const professorNames = Array.from(new Set(courseProfessorCatalog.flatMap(entry => entry.professors))).sort((a, b) => a.localeCompare(b, 'es'));
