-- FIQT Reviews: datos ficticios de demostración. No cargar información personal de docentes.
create extension if not exists "pgcrypto";

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade, full_name text,
  student_code text, faculty text, role text not null default 'student' check (role in ('student','admin')),
  verification_status text not null default 'unverified' check (verification_status in ('unverified','pending','verified','rejected')),
  created_at timestamptz not null default now()
);
create table public.cycles (id serial primary key, number int unique not null check (number between 1 and 10), name text not null);
create table public.courses (id uuid primary key default gen_random_uuid(), cycle_id int references public.cycles(id), code text, name text not null, credits int, created_at timestamptz not null default now());
create table public.professors (id uuid primary key default gen_random_uuid(), full_name text not null, photo_url text, source_name text not null default 'DIRCE UNI', source_url text, is_active boolean not null default true, created_at timestamptz not null default now());
create table public.course_professors (id uuid primary key default gen_random_uuid(), course_id uuid not null references public.courses(id) on delete cascade, professor_id uuid not null references public.professors(id) on delete cascade, academic_term text, section text, unique(course_id, professor_id, academic_term, section));
create table public.verified_courses (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, course_id uuid not null references public.courses(id), academic_term text, section text, verified_by uuid references auth.users(id), created_at timestamptz not null default now(), unique(user_id, course_id, academic_term, section));
create table public.verification_submissions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, file_url text not null, status text not null default 'pending' check(status in ('pending','approved','rejected')), admin_notes text, created_at timestamptz not null default now(), reviewed_at timestamptz, reviewed_by uuid references auth.users(id));
create table public.reviews (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, professor_id uuid not null references public.professors(id), course_id uuid not null references public.courses(id), clarity_rating int not null check(clarity_rating between 1 and 5), difficulty_rating int not null check(difficulty_rating between 1 and 5), fairness_rating int not null check(fairness_rating between 1 and 5), treatment_rating int not null check(treatment_rating between 1 and 5), workload_rating int not null check(workload_rating between 1 and 5), recommendation text not null check(recommendation in ('like','dislike')), selected_tags text[] not null default '{}', comment text not null check(char_length(comment) between 1 and 600), status text not null default 'pending' check(status in ('pending','approved','rejected')), moderation_reason text, created_at timestamptz not null default now(), unique(user_id, professor_id, course_id));
create table public.review_reports (id uuid primary key default gen_random_uuid(), review_id uuid not null references public.reviews(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, reason text not null, created_at timestamptz not null default now(), unique(review_id,user_id));

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin') $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name','')); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create or replace function public.can_review_course(p_course uuid) returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.verified_courses where user_id=auth.uid() and course_id=p_course) $$;
create or replace function public.enforce_review_rules() returns trigger language plpgsql security definer set search_path = public as $$ begin if new.user_id <> auth.uid() then raise exception 'No puedes reseñar por otro usuario'; end if; if not public.can_review_course(new.course_id) then raise exception 'Para reseñar este curso, primero debes verificar que lo llevaste'; end if; if new.comment ~* '\m(corrupto|corrupta|acosador|acosadora|ladr[oó]n|ladrona|idiota|imb[eé]cil|mierda|puta|maric[oó]n)\M' then raise exception 'Tu reseña debe enfocarse en la experiencia académica y mantener un lenguaje respetuoso.'; end if; new.status := 'pending'; return new; end; $$;
create trigger reviews_before_insert before insert on public.reviews for each row execute function public.enforce_review_rules();

alter table public.profiles enable row level security; alter table public.cycles enable row level security; alter table public.courses enable row level security; alter table public.professors enable row level security; alter table public.course_professors enable row level security; alter table public.verified_courses enable row level security; alter table public.verification_submissions enable row level security; alter table public.reviews enable row level security; alter table public.review_reports enable row level security;
create policy "profiles own read" on public.profiles for select using (id=auth.uid() or public.is_admin()); create policy "profiles admin update" on public.profiles for update using (public.is_admin()) with check (public.is_admin());
create policy "catalog public read" on public.cycles for select using (true); create policy "catalog admin manage" on public.cycles for all using (public.is_admin()) with check (public.is_admin());
create policy "courses public read" on public.courses for select using (true); create policy "courses admin manage" on public.courses for all using (public.is_admin()) with check (public.is_admin());
create policy "professors public read" on public.professors for select using (is_active or public.is_admin()); create policy "professors admin manage" on public.professors for all using (public.is_admin()) with check (public.is_admin());
create policy "links public read" on public.course_professors for select using (true); create policy "links admin manage" on public.course_professors for all using (public.is_admin()) with check (public.is_admin());
create policy "verified own or admin" on public.verified_courses for select using (user_id=auth.uid() or public.is_admin()); create policy "verified admin manage" on public.verified_courses for all using (public.is_admin()) with check (public.is_admin());
create policy "submissions own or admin read" on public.verification_submissions for select using (user_id=auth.uid() or public.is_admin()); create policy "submissions own insert" on public.verification_submissions for insert with check (user_id=auth.uid()); create policy "submissions admin update" on public.verification_submissions for update using (public.is_admin()) with check (public.is_admin());
create policy "reviews public approved or owner/admin" on public.reviews for select using (status='approved' or user_id=auth.uid() or public.is_admin()); create policy "reviews own insert" on public.reviews for insert with check (user_id=auth.uid()); create policy "reviews own update pending" on public.reviews for update using (user_id=auth.uid() and status='pending') with check (user_id=auth.uid() and status='pending'); create policy "reviews admin update" on public.reviews for update using (public.is_admin()) with check(public.is_admin());
create policy "reports own insert" on public.review_reports for insert with check(user_id=auth.uid()); create policy "reports own or admin read" on public.review_reports for select using(user_id=auth.uid() or public.is_admin());

insert into storage.buckets (id,name,public) values ('verification-evidence','verification-evidence',false) on conflict do nothing;
create policy "upload own verification evidence" on storage.objects for insert to authenticated with check (bucket_id='verification-evidence' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "read own or admin evidence" on storage.objects for select to authenticated using (bucket_id='verification-evidence' and ((storage.foldername(name))[1]=auth.uid()::text or public.is_admin()));

insert into public.cycles(number,name) values (1,'Primer ciclo'),(2,'Segundo ciclo'),(3,'Tercer ciclo'),(4,'Cuarto ciclo'),(5,'Quinto ciclo'),(6,'Sexto ciclo'),(7,'Séptimo ciclo'),(8,'Octavo ciclo'),(9,'Noveno ciclo'),(10,'Décimo ciclo') on conflict(number) do nothing;
insert into public.courses(cycle_id,code,name,credits) values ((select id from public.cycles where number=1),'MAT-101','Matemática I (ejemplo)',4),((select id from public.cycles where number=1),'QUI-101','Química General (ejemplo)',4),((select id from public.cycles where number=2),'MAT-201','Matemática II (ejemplo)',4),((select id from public.cycles where number=3),'ING-301','Introducción a la Ingeniería (ejemplo)',3);
insert into public.professors(full_name,source_name) values ('Dra. Elena Prado (ejemplo)','DIRCE UNI'),('Mg. Luis Campos (ejemplo)','DIRCE UNI'),('Ing. Sofía Ríos (ejemplo)','DIRCE UNI');
insert into public.course_professors(course_id,professor_id) select c.id,p.id from public.courses c cross join public.professors p where c.code='MAT-101' and p.full_name='Dra. Elena Prado (ejemplo)';
insert into public.course_professors(course_id,professor_id) select c.id,p.id from public.courses c cross join public.professors p where c.code='QUI-101' and p.full_name='Mg. Luis Campos (ejemplo)';
insert into public.course_professors(course_id,professor_id) select c.id,p.id from public.courses c cross join public.professors p where c.code='ING-301' and p.full_name='Ing. Sofía Ríos (ejemplo)';
-- Para habilitar el primer administrador, después de crear su cuenta ejecuta:
-- update public.profiles set role='admin' where id='UUID_DEL_USUARIO';
